name: CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  APP_NAME: ${{ 'chores-shellac' }}
jobs:
  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker Build
        run: docker login --username=_ --password=cdc21d38-df69-4376-ac20-9b8b448fa2fe registry.heroku.com
      - name: Publish
        run: |
          heroku container:push web -a $APP_NAME
          heroku container:release web -a $APP_NAME
