name: Coverage
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Run Coverage
        run: |
          chmod +x gradlew
          ./gradlew jacocoTestReport
      - name: Report Coverage
        id: jacoco
        uses: madrapps/jacoco-report@v1.2
        with:
          paths: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
          min-coverage-overall: 100
          min-coverage-changed-files: 100